version: "3.7"

volumes:
  db-data:

services:
  api:
    container_name: api
    restart: always
    build:
      context: .
    volumes:
      - .:/web
    ports:
      - 8000:8000
    command: sh -c "python manage.py migrate &&
                    uvicorn djapi.asgi:application --host 0.0.0.0 --port 8000"
